server:
  port: 7788
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangpeng849/SpringcloudConfig
          proxy:
            https:
              host: 10.191.131.156
              port: '3128'
          search-paths: myspringcloudconfig
      label: master
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://wangp:lingh@127.0.0.1:8100/eureka/,http://wangp:lingh@127.0.0.1:9100/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    instance-id: ${spring.application.name}###${server.port} #指定实例id
